import numpy as np
import matplotlib.pyplot as plt
from Needfunctions import Bistability
from mpl_toolkits.mplot3d import Axes3D
import os
from Preparation_WXH import save_file as sf

## 2D演化图
forwardsin1=np.loadtxt(r'f:\change fre\bistable date\fd step=1kHz\forwards.txt')
backwardsin1=np.loadtxt(r'f:\change fre\bistable date\fd step=1kHz\backwards.txt')
evo_timesin1=np.loadtxt(r'f:\change fre\bistable date\fd step=1kHz\evo_times.txt')
delta_Psin1=np.loadtxt(r'f:\change fre\bistable date\fd step=1kHz\delta_fs.txt')

forwardsin2=np.loadtxt(r'f:\change fre\bistable date\fd step=0.5kHz\forwards.txt')
backwardsin2=np.loadtxt(r'f:\change fre\bistable date\fd step=0.5kHz\backwards.txt')
evo_timesin2=np.loadtxt(r'f:\change fre\bistable date\fd step=0.5kHz\evo_times.txt')
delta_Psin2=np.loadtxt(r'f:\change fre\bistable date\fd step=0.5kHz\delta_fs.txt')


# forwardsin3=np.loadtxt(r'f:\change fre\bistable date\fd step=0.03kHz\forwards.txt')
# backwardsin3=np.loadtxt(r'f:\change fre\bistable date\fd step=0.03kHz\backwards.txt')
# evo_timesin3=np.loadtxt(r'f:\change fre\bistable date\fd step=0.03kHz\evo_times.txt')
# delta_Psin3=np.loadtxt(r'f:\change fre\bistable date\fd step=0.03kHz\delta_fs.txt')
# forwardsin2=np.loadtxt(r'f:\change fre\bistable date\fd step=1000.0kHz\forwards.txt')
# backwardsin2=np.loadtxt(r'f:\change fre\bistable date\fd step=1000.0kHz\backwards.txt')
# evo_timesin2=np.loadtxt(r'f:\change fre\bistable date\fd step=1000.0kHz\evo_times.txt')
# delta_Psin2=np.loadtxt(r'f:\change fre\bistable date\fd step=1000.0kHz\delta_fs.txt')
#
#
# forwardsin3=np.loadtxt(r'f:\change fre\bistable date\fd step=1.0kHz\forwards.txt')
# backwardsin3=np.loadtxt(r'f:\change fre\bistable date\fd step=1.0kHz\backwards.txt')
# evo_timesin3=np.loadtxt(r'f:\change fre\bistable date\fd step=1.0kHz\evo_times.txt')
# delta_Psin3=np.loadtxt(r'f:\change fre\bistable date\fd step=1.0kHz\delta_fs.txt')

middle_number=50
# # print(np.shape(forwardsin1))
plt.figure(figsize=(12,12))
ax1 = plt.subplot(111)
ax1.plot(evo_timesin1[::middle_number], forwardsin1[::middle_number], 's',  markersize=4, label=r'$Re[m,W \longrightarrow X],0.01kHz$',markerfacecolor='None')
ax1.plot(evo_timesin2[::middle_number], forwardsin2[::middle_number], 's',  markersize=4, label=r'$Re[m,W \longrightarrow X],1000kHz$',markerfacecolor='None')
# ax1.plot(evo_timesin3[::middle_number], forwardsin3[::middle_number], 's',  markersize=4, label=r'$Re[m,W \longrightarrow X],1kHz$',markerfacecolor='None')

ax1.set_xlabel(r'$times$ [s]',fontsize=20)
ax1.set_ylabel(r'$\Delta_+/2\pi$',fontsize=20)
plt.tick_params(labelsize=20)
plt.legend()
plt.show()
#
plt.figure(figsize=(12,12))
ax1 = plt.subplot(111)
ax1.plot(evo_timesin1[::middle_number], backwardsin1[::middle_number], 's',  markersize=4, label=r'$Re[m,Y \longrightarrow Z],0.01kHz$',markerfacecolor='None')
ax1.plot(evo_timesin2[::middle_number], backwardsin2[::middle_number], 's',  markersize=4, label=r'$Re[m,Y \longrightarrow Z],1000kHz$',markerfacecolor='None')
# ax1.plot(evo_timesin3[::middle_number], backwardsin3[::middle_number], 's',  markersize=4, label=r'$Re[m,W \longrightarrow X],1kHz$',markerfacecolor='None')
ax1.set_xlabel(r'$times$ [s]',fontsize=20)
ax1.set_ylabel(r'$\Delta_+/2\pi$',fontsize=20)
plt.tick_params(labelsize=20)
plt.legend()
plt.show()

# #  3D演化图
# forwardsin1r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=0.01kHz\forwards real.txt')
# forwardsin1i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=0.01kHz\forwards imag.txt')
# backwardsin1r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=0.01kHz\backwards real.txt')
# backwardsin1i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=0.01kHz\backwards imag.txt')
# evo_timesin1=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=0.01kHz\evo_times.txt')
# delta_Psin1=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=0.01kHz\delta_fs.txt')

# forwardsin2r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1.0kHz\forwards.txt')
# forwardsin2i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1.0kHz\forwards.txt')
# backwardsin2r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1.0kHz\backwards.txt')
# backwardsin2i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1.0kHz\backwards.txt')
#
# forwardsin3r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=10.0kHz\forwards.txt')
# forwardsin3i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=10.0kHz\forwards.txt')
# backwardsin3r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=10.0kHz\backwards.txt')
# backwardsin3i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=10.0kHz\backwards.txt')
# #
# forwardsin4r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1000.0kHz\forwards.txt')
# forwardsin4i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1000.0kHz\forwards.txt')
# backwardsin4r=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1000.0kHz\backwards.txt')
# backwardsin4i=np.loadtxt(r'F:\change fre\bistable date real and imag\fd step=1000.0kHz\backwards.txt')

# middle_number=500

# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(forwardsin1i[::middle_number],evo_timesin1[::middle_number],forwardsin1r[::middle_number],'-o', color='red',markersize=4,markerfacecolor='None',label='$W \longrightarrow X$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()

# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(backwardsin1i[::middle_number],evo_timesin1[::middle_number],backwardsin1r[::middle_number],'-o', color='blue',markersize=4,markerfacecolor='None',label='$Y \longrightarrow Z$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()

# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(forwardsin2i[::middle_number],evo_timesin1[::middle_number],forwardsin2r[::middle_number],'-o', color='red',markersize=4,markerfacecolor='None',label='$W \longrightarrow X$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()
#
# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(backwardsin2i[::middle_number],evo_timesin1[::middle_number],backwardsin2r[::middle_number],'-o', color='blue',markersize=4,markerfacecolor='None',label='$Y \longrightarrow Z$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()

# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(forwardsin3i[::middle_number],evo_timesin1[::middle_number],forwardsin3r[::middle_number],'-o', color='red',markersize=4,markerfacecolor='None',label='$W \longrightarrow X$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()
#
# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(backwardsin3i[::middle_number],evo_timesin1[::middle_number],backwardsin3r[::middle_number],'-o', color='blue',markersize=4,markerfacecolor='None',label='$Y \longrightarrow Z$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()
#
# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(forwardsin4i[::middle_number],evo_timesin1[::middle_number],forwardsin4r[::middle_number],'-o', color='red',markersize=4,markerfacecolor='None',label='$W \longrightarrow X$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()
#
# fig=plt.figure(figsize=(12, 6))
# ax=fig.add_subplot(1,1,1,projection='3d')
# ax=Axes3D(fig)
# fig.add_axes(ax)
# ax.set_box_aspect([1,2,1])
# ax.plot(backwardsin4i[::middle_number],evo_timesin1[::middle_number],backwardsin4r[::middle_number],'-o', color='blue',markersize=4,markerfacecolor='None',label='$Y \longrightarrow Z$')
# ax.set_xlabel(r'Imag', fontsize=10)
# ax.set_ylabel(r'time', fontsize=10)
# ax.set_zlabel(r'Real', fontsize=10)
# # ax.set_ylim(0,10)
# # ax.set_xlim(-60,60)
# # plt.xticks([-50,0,50],['-50','0','50'])
# # ax.grid(None)
# ax.view_init(elev=25, azim=40)
# plt.legend(loc=0)
# plt.show()
